/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../router/Router`; params?: Router.UnknownInputParams; } | { pathname: `/../src/checkers`; params?: Router.UnknownInputParams; } | { pathname: `/../src/weather`; params?: Router.UnknownInputParams; } | { pathname: `/../src/calculator`; params?: Router.UnknownInputParams; } | { pathname: `/../src/clicker`; params?: Router.UnknownInputParams; } | { pathname: `/../components/calculatorNumbers`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../router/Router`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/checkers`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/weather`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/calculator`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/clicker`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/calculatorNumbers`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../router/Router${`?${string}` | `#${string}` | ''}` | `/../src/checkers${`?${string}` | `#${string}` | ''}` | `/../src/weather${`?${string}` | `#${string}` | ''}` | `/../src/calculator${`?${string}` | `#${string}` | ''}` | `/../src/clicker${`?${string}` | `#${string}` | ''}` | `/../components/calculatorNumbers${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../router/Router`; params?: Router.UnknownInputParams; } | { pathname: `/../src/checkers`; params?: Router.UnknownInputParams; } | { pathname: `/../src/weather`; params?: Router.UnknownInputParams; } | { pathname: `/../src/calculator`; params?: Router.UnknownInputParams; } | { pathname: `/../src/clicker`; params?: Router.UnknownInputParams; } | { pathname: `/../components/calculatorNumbers`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
