/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/Numpad`; params?: Router.UnknownInputParams; } | { pathname: `/../components/NumberField`; params?: Router.UnknownInputParams; } | { pathname: `/../src/RouterPage`; params?: Router.UnknownInputParams; } | { pathname: `/../components/calculatortest`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CalculatorTest`; params?: Router.UnknownInputParams; } | { pathname: `/../src/calculatorPage`; params?: Router.UnknownInputParams; } | { pathname: `/Router`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Row`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/Numpad`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/NumberField`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/RouterPage`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/calculatortest`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/CalculatorTest`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/calculatorPage`; params?: Router.UnknownOutputParams; } | { pathname: `/Router`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Button`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Row`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/Numpad${`?${string}` | `#${string}` | ''}` | `/../components/NumberField${`?${string}` | `#${string}` | ''}` | `/../src/RouterPage${`?${string}` | `#${string}` | ''}` | `/../components/calculatortest${`?${string}` | `#${string}` | ''}` | `/../components/CalculatorTest${`?${string}` | `#${string}` | ''}` | `/../src/calculatorPage${`?${string}` | `#${string}` | ''}` | `/Router${`?${string}` | `#${string}` | ''}` | `/../components/Button${`?${string}` | `#${string}` | ''}` | `/../components/Row${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/Numpad`; params?: Router.UnknownInputParams; } | { pathname: `/../components/NumberField`; params?: Router.UnknownInputParams; } | { pathname: `/../src/RouterPage`; params?: Router.UnknownInputParams; } | { pathname: `/../components/calculatortest`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CalculatorTest`; params?: Router.UnknownInputParams; } | { pathname: `/../src/calculatorPage`; params?: Router.UnknownInputParams; } | { pathname: `/Router`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Row`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
